### ISSUE TITLE
Modal width spec differs with style portal.

### ISSUE THREAD

**Issue by ashleyyang0610** [trendmicro-frontend/react-modal#1]
http://style-portal.tw.trendnet.org/#/styles/minimalism/latest/348487b9-82cc-4c06-98e4-ede8ac73a42b
As the spec in style portal, it should replace `min-width` and `max-width` property with `width`.
- Extra small:W400 x H240 px (minimum height)
- Small:W544 x H304 px (minimum height)
- Medium:W688 x H304 px (minimum height)
- Large:W928 x H304 px (minimum height)

**Comment by cheton** [comment]
@ashleyyang0610 

Below is current behavior that will automatically adjust the width with respect to the given modal size and the content width. May I know what problems you encountered?

#### Extra Small (xs)
```css
min-width: 400px;
max-width: 543px;
```

#### Small (sm)
```css
min-width: 544px;
max-width: 687px;
```

#### Medium (md)
```css
min-width: 688px;
max-width: 927px;
```

#### Large (lg)
```css
min-width: 928px;
```

**Comment by ashleyyang0610** [comment]
@cheton 
In style portal, modal width won't be automatically adjusted according to modal content.
Please help check again. Thanks.
